// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: lang_compare.proto
#ifndef GRPC_lang_5fcompare_2eproto__INCLUDED
#define GRPC_lang_5fcompare_2eproto__INCLUDED

#include "lang_compare.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace langcompare {

// The greeting service definition.
class LangCompare final {
 public:
  static constexpr char const* service_full_name() {
    return "langcompare.LangCompare";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status XorCipher(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest& request, ::langcompare::XorCipherReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::langcompare::XorCipherReply>> AsyncXorCipher(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::langcompare::XorCipherReply>>(AsyncXorCipherRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::langcompare::XorCipherReply>> PrepareAsyncXorCipher(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::langcompare::XorCipherReply>>(PrepareAsyncXorCipherRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void XorCipher(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest* request, ::langcompare::XorCipherReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void XorCipher(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::langcompare::XorCipherReply* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::langcompare::XorCipherReply>* AsyncXorCipherRaw(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::langcompare::XorCipherReply>* PrepareAsyncXorCipherRaw(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status XorCipher(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest& request, ::langcompare::XorCipherReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::langcompare::XorCipherReply>> AsyncXorCipher(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::langcompare::XorCipherReply>>(AsyncXorCipherRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::langcompare::XorCipherReply>> PrepareAsyncXorCipher(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::langcompare::XorCipherReply>>(PrepareAsyncXorCipherRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void XorCipher(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest* request, ::langcompare::XorCipherReply* response, std::function<void(::grpc::Status)>) override;
      void XorCipher(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::langcompare::XorCipherReply* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::langcompare::XorCipherReply>* AsyncXorCipherRaw(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::langcompare::XorCipherReply>* PrepareAsyncXorCipherRaw(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_XorCipher_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status XorCipher(::grpc::ServerContext* context, const ::langcompare::XorCipherRequest* request, ::langcompare::XorCipherReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_XorCipher : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_XorCipher() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_XorCipher() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status XorCipher(::grpc::ServerContext* context, const ::langcompare::XorCipherRequest* request, ::langcompare::XorCipherReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestXorCipher(::grpc::ServerContext* context, ::langcompare::XorCipherRequest* request, ::grpc::ServerAsyncResponseWriter< ::langcompare::XorCipherReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_XorCipher<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_XorCipher : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_XorCipher() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::langcompare::XorCipherRequest, ::langcompare::XorCipherReply>(
          [this](::grpc::ServerContext* context,
                 const ::langcompare::XorCipherRequest* request,
                 ::langcompare::XorCipherReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->XorCipher(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_XorCipher() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status XorCipher(::grpc::ServerContext* context, const ::langcompare::XorCipherRequest* request, ::langcompare::XorCipherReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void XorCipher(::grpc::ServerContext* context, const ::langcompare::XorCipherRequest* request, ::langcompare::XorCipherReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_XorCipher<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_XorCipher : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_XorCipher() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_XorCipher() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status XorCipher(::grpc::ServerContext* context, const ::langcompare::XorCipherRequest* request, ::langcompare::XorCipherReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_XorCipher : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_XorCipher() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_XorCipher() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status XorCipher(::grpc::ServerContext* context, const ::langcompare::XorCipherRequest* request, ::langcompare::XorCipherReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestXorCipher(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_XorCipher : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_XorCipher() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->XorCipher(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_XorCipher() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status XorCipher(::grpc::ServerContext* context, const ::langcompare::XorCipherRequest* request, ::langcompare::XorCipherReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void XorCipher(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_XorCipher : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_XorCipher() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::langcompare::XorCipherRequest, ::langcompare::XorCipherReply>(std::bind(&WithStreamedUnaryMethod_XorCipher<BaseClass>::StreamedXorCipher, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_XorCipher() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status XorCipher(::grpc::ServerContext* context, const ::langcompare::XorCipherRequest* request, ::langcompare::XorCipherReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedXorCipher(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::langcompare::XorCipherRequest,::langcompare::XorCipherReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_XorCipher<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_XorCipher<Service > StreamedService;
};

}  // namespace langcompare


#endif  // GRPC_lang_5fcompare_2eproto__INCLUDED
