// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: lang_compare.proto

#include "lang_compare.pb.h"
#include "lang_compare.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace langcompare {

static const char* LangCompare_method_names[] = {
  "/langcompare.LangCompare/XorCipher",
};

std::unique_ptr< LangCompare::Stub> LangCompare::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LangCompare::Stub> stub(new LangCompare::Stub(channel));
  return stub;
}

LangCompare::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_XorCipher_(LangCompare_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LangCompare::Stub::XorCipher(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest& request, ::langcompare::XorCipherReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_XorCipher_, context, request, response);
}

void LangCompare::Stub::experimental_async::XorCipher(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest* request, ::langcompare::XorCipherReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_XorCipher_, context, request, response, std::move(f));
}

void LangCompare::Stub::experimental_async::XorCipher(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::langcompare::XorCipherReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_XorCipher_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::langcompare::XorCipherReply>* LangCompare::Stub::AsyncXorCipherRaw(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::langcompare::XorCipherReply>::Create(channel_.get(), cq, rpcmethod_XorCipher_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::langcompare::XorCipherReply>* LangCompare::Stub::PrepareAsyncXorCipherRaw(::grpc::ClientContext* context, const ::langcompare::XorCipherRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::langcompare::XorCipherReply>::Create(channel_.get(), cq, rpcmethod_XorCipher_, context, request, false);
}

LangCompare::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LangCompare_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LangCompare::Service, ::langcompare::XorCipherRequest, ::langcompare::XorCipherReply>(
          std::mem_fn(&LangCompare::Service::XorCipher), this)));
}

LangCompare::Service::~Service() {
}

::grpc::Status LangCompare::Service::XorCipher(::grpc::ServerContext* context, const ::langcompare::XorCipherRequest* request, ::langcompare::XorCipherReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace langcompare

