[package]
name = "stub"
version = "0.1.0"
authors = ["roycrippen <roycrippen@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
prost = "0.5"
tower-grpc = { version = "0.1.0", features = ["tower-hyper"] }
yaml-rust = "0.4"

