# language compare using gRPC configuration


# servers providing function execution
servers:
  # python gRPC test server
  py_example:
    type: py
    port: 50051
    cmd: python3 server_example.py

  # cpp gRPC test server
  # port is currently hard coded to 50052 in cpp source code
  # don't change the port number below
  cpp_example:
    type: cpp
    port: 50052
    cmd: ../cpp/server_example

#  - go:    # go gRPC server
#      type: go
#      port: 50053
#      cmd: ../cpp/lang_compare_server


# available test runners to compare function results from multiple languages
runners:
  # compare language implementations of xor cipher
  # current implementations: py vs cpp
  test_xor_cipher:
    cmd: pytest test_xor_cipher.py --hypothesis-show-statistics --disable-warnings -v

  # test that each server type is working
  # current servers tested: [py, cpp]
  test_servers:
    cmd: pytest test_servers.py --hypothesis-show-statistics --disable-warnings -v


# list of runs to execute
runs:
  - test_servers
  - test_xor_cipher

