# language compare using gRPC configuration

# servers providing the requested function execution
servers:
  - py:     # python gRPC server
      type: py
      port: 50052
      cmd: python3 lang_compare_server.py

  - cpp:    # cpp gRPC server
      type: cpp
      port: 50051
      cmd: ../cpp/lang_compare_server

# test runner to compare function results from multiple languages
runners:
  - test_xor_cipher:
      type: py
      cmd: python3 -W ignore -m unittest -v test_xor_cipher.py
      langs:
        - py
        - cpp

  - test_servers:
      type: py
      cmd: python3 -W ignore -m unittest -v test_servers.py
      langs:
        - py
        - cpp
        - cpp

# list of runs to execute
runs:
  #  - test_xor_cipher
  - test_servers
  - test_servers

