# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lang_compare.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lang_compare.proto',
  package='langcompare',
  syntax='proto3',
  serialized_options=_b('\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x12lang_compare.proto\x12\x0blangcompare\"/\n\x10XorCipherRequest\x12\x0e\n\x06in_str\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"!\n\x0eXorCipherReply\x12\x0f\n\x07out_str\x18\x01 \x01(\t2X\n\x0bLangCompare\x12I\n\tXorCipher\x12\x1d.langcompare.XorCipherRequest\x1a\x1b.langcompare.XorCipherReply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_XORCIPHERREQUEST = _descriptor.Descriptor(
  name='XorCipherRequest',
  full_name='langcompare.XorCipherRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='in_str', full_name='langcompare.XorCipherRequest.in_str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='langcompare.XorCipherRequest.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=82,
)


_XORCIPHERREPLY = _descriptor.Descriptor(
  name='XorCipherReply',
  full_name='langcompare.XorCipherReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='out_str', full_name='langcompare.XorCipherReply.out_str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['XorCipherRequest'] = _XORCIPHERREQUEST
DESCRIPTOR.message_types_by_name['XorCipherReply'] = _XORCIPHERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XorCipherRequest = _reflection.GeneratedProtocolMessageType('XorCipherRequest', (_message.Message,), {
  'DESCRIPTOR' : _XORCIPHERREQUEST,
  '__module__' : 'lang_compare_pb2'
  # @@protoc_insertion_point(class_scope:langcompare.XorCipherRequest)
  })
_sym_db.RegisterMessage(XorCipherRequest)

XorCipherReply = _reflection.GeneratedProtocolMessageType('XorCipherReply', (_message.Message,), {
  'DESCRIPTOR' : _XORCIPHERREPLY,
  '__module__' : 'lang_compare_pb2'
  # @@protoc_insertion_point(class_scope:langcompare.XorCipherReply)
  })
_sym_db.RegisterMessage(XorCipherReply)


DESCRIPTOR._options = None

_LANGCOMPARE = _descriptor.ServiceDescriptor(
  name='LangCompare',
  full_name='langcompare.LangCompare',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=119,
  serialized_end=207,
  methods=[
  _descriptor.MethodDescriptor(
    name='XorCipher',
    full_name='langcompare.LangCompare.XorCipher',
    index=0,
    containing_service=None,
    input_type=_XORCIPHERREQUEST,
    output_type=_XORCIPHERREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LANGCOMPARE)

DESCRIPTOR.services_by_name['LangCompare'] = _LANGCOMPARE

# @@protoc_insertion_point(module_scope)
